
include(cage_assets)
include(cage_build_configuration)
include(cage_build_destination)
include(cage_copy_redist)
include(cage_default_init)
include(cage_directory_link)
include(cage_disable_source_build)
include(cage_ide_category)
include(cage_ide_sort_files)
include(cage_ide_working_dir)
include(cage_print_all_variables)
include(cage_print_target_properties)
include(cage_target_api_macro)
