
function(cage_list_all_targets out_var current_dir)
	get_property(targets DIRECTORY ${current_dir} PROPERTY BUILDSYSTEM_TARGETS)
	get_property(subdirs DIRECTORY ${current_dir} PROPERTY SUBDIRECTORIES)
	foreach(subdir ${subdirs})
		cage_list_all_targets(subdir_targets ${subdir})
		list(APPEND targets ${subdir_targets})
	endforeach(subdir)
	set(${out_var} ${targets} PARENT_SCOPE)
endfunction()
