
set(cage_output_redist_source "${CMAKE_CURRENT_LIST_DIR}")

function(cage_output_redist where)
	configure_file("${cage_output_redist_source}/../externals/assimp/assimp/LICENSE" "${where}/redist/assimp" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/devil/devil/LICENSE" "${where}/redist/devil" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/fastnoise/fastnoise/LICENSE" "${where}/redist/fastnoise" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/freetype/freetype/docs/LICENSE.TXT" "${where}/redist/freetype" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/freetype/freetype/docs/FTL.TXT" "${where}/redist/freetype_ftl" COPYONLY)
	#configure_file("${cage_output_redist_source}/../externals/freetype/freetype/docs/GPLv2.TXT" "${where}/redist/freetype_gpl" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/glfw/glfw/LICENSE.md" "${where}/redist/glfw" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/glm/glm/manual.md" "${where}/redist/glm" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/jpeg/jpeg/LICENSE.md" "${where}/redist/jpeg" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/libpng/libpng/LICENSE" "${where}/redist/png" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/libsoundio/libsoundio/LICENSE" "${where}/redist/soundio" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/libtiff/libtiff/COPYRIGHT" "${where}/redist/tiff" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/msdfgen/msdfgen/LICENSE.txt" "${where}/redist/msdfgen" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/ogg/ogg/COPYING" "${where}/redist/ogg" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/simplefilewatcher/simplefilewatcher/License.txt" "${where}/redist/simplefilewatcher" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/utfcpp/utfcpp/LICENSE" "${where}/redist/utfcpp" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/vorbis/vorbis/COPYING" "${where}/redist/vorbis" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/xsimd/xsimd/LICENSE" "${where}/redist/xsimd" COPYONLY)
	configure_file("${cage_output_redist_source}/../externals/zlib/zlib/README" "${where}/redist/zlib" COPYONLY)
	configure_file("${cage_output_redist_source}/../LICENSE" "${where}/redist/cage" COPYONLY)
endfunction(cage_output_redist)

