
function(cage_ide_sort_files target)
	get_property(files TARGET ${target} PROPERTY SOURCES)
	if(ARGV1)
		set(root "${ARGV1}")
	else()
		set(root "${CMAKE_CURRENT_SOURCE_DIR}")
	endif()
	unset(files2)
	foreach(f ${files})
		cmake_path(IS_PREFIX root "${f}" NORMALIZE ok)
		if(ok)
			list(APPEND files2 "${f}")
		endif()
	endforeach()
	source_group(TREE "${root}" FILES ${files2})
endfunction(cage_ide_sort_files)

