
/*
$define allowParsingHash true
*/

#define CAGE_SHADER_MAX_MESHES 85
#define CAGE_SHADER_MAX_LIGHTS 170
#define CAGE_SHADER_MAX_BONES 340
#define CAGE_SHADER_MAX_OPTIONS 16
#define CAGE_SHADER_MAX_SHADOWMAPS2D 8
#define CAGE_SHADER_MAX_SHADOWMAPSCUBE 8
#define CAGE_SHADER_MAX_LIGHTINTENSITYTHRESHOLD 0.05

// attribute in locations

#define CAGE_SHADER_ATTRIB_IN_POSITION 0
#define CAGE_SHADER_ATTRIB_IN_NORMAL 1
#define CAGE_SHADER_ATTRIB_IN_BONEINDEX 2
#define CAGE_SHADER_ATTRIB_IN_BONEWEIGHT 3
#define CAGE_SHADER_ATTRIB_IN_UV 4
#define CAGE_SHADER_ATTRIB_IN_AUX0 5

// texture sampler bindings

#define CAGE_SHADER_TEXTURE_ALBEDO 0
#define CAGE_SHADER_TEXTURE_SPECIAL 1
#define CAGE_SHADER_TEXTURE_NORMAL 2
#define CAGE_SHADER_TEXTURE_ALBEDO_ARRAY 3
#define CAGE_SHADER_TEXTURE_SPECIAL_ARRAY 4
#define CAGE_SHADER_TEXTURE_NORMAL_ARRAY 5
#define CAGE_SHADER_TEXTURE_ALBEDO_CUBE 6
#define CAGE_SHADER_TEXTURE_SPECIAL_CUBE 7
#define CAGE_SHADER_TEXTURE_NORMAL_CUBE 8
#define CAGE_SHADER_TEXTURE_CUSTOM 9
#define CAGE_SHADER_TEXTURE_SSAO 10
#define CAGE_SHADER_TEXTURE_DEPTH 11
#define CAGE_SHADER_TEXTURE_SHADOWMAP2D0 16
#define CAGE_SHADER_TEXTURE_SHADOWMAPCUBE0 24

// uniform block bindings

#define CAGE_SHADER_UNIBLOCK_VIEWPORT 0
#define CAGE_SHADER_UNIBLOCK_MATERIAL 1
#define CAGE_SHADER_UNIBLOCK_MESHES 2
#define CAGE_SHADER_UNIBLOCK_ARMATURES 3
#define CAGE_SHADER_UNIBLOCK_LIGHTS 4
#define CAGE_SHADER_UNIBLOCK_SHADOWEDLIGHTS 5
#define CAGE_SHADER_UNIBLOCK_OPTIONS 6
#define CAGE_SHADER_UNIBLOCK_CUSTOMDATA 7

// options indices

#define CAGE_SHADER_OPTIONINDEX_MAPALBEDO 1
#define CAGE_SHADER_OPTIONINDEX_MAPSPECIAL 2
#define CAGE_SHADER_OPTIONINDEX_MAPNORMAL 3
#define CAGE_SHADER_OPTIONINDEX_AMBIENTOCCLUSION 4
#define CAGE_SHADER_OPTIONINDEX_SKELETON 5
#define CAGE_SHADER_OPTIONINDEX_BONESCOUNT 6
#define CAGE_SHADER_OPTIONINDEX_LIGHTSCOUNT 7
#define CAGE_SHADER_OPTIONINDEX_SHADOWEDLIGHTSCOUNT 8

// options values

#define CAGE_SHADER_OPTIONVALUE_MAPALBEDO2D 1
#define CAGE_SHADER_OPTIONVALUE_MAPALBEDOARRAY 2
#define CAGE_SHADER_OPTIONVALUE_MAPALBEDOCUBE 3
#define CAGE_SHADER_OPTIONVALUE_MAPSPECIAL2D 4
#define CAGE_SHADER_OPTIONVALUE_MAPSPECIALARRAY 5
#define CAGE_SHADER_OPTIONVALUE_MAPSPECIALCUBE 6
#define CAGE_SHADER_OPTIONVALUE_MAPNORMAL2D 7
#define CAGE_SHADER_OPTIONVALUE_MAPNORMALARRAY 8
#define CAGE_SHADER_OPTIONVALUE_MAPNORMALCUBE 9
#define CAGE_SHADER_OPTIONVALUE_LIGHTDIRECTIONAL 11
#define CAGE_SHADER_OPTIONVALUE_LIGHTDIRECTIONALSHADOW 12
#define CAGE_SHADER_OPTIONVALUE_LIGHTSPOT 13
#define CAGE_SHADER_OPTIONVALUE_LIGHTSPOTSHADOW 14
#define CAGE_SHADER_OPTIONVALUE_LIGHTPOINT 15
#define CAGE_SHADER_OPTIONVALUE_LIGHTPOINTSHADOW 16

/*
$undef allowParsingHash
*/
